# Deep Learning 

# Gradient Descent With Three Features and 1 Example (Assignment 2)

In [9]:
import math 
import numpy as np

In [53]:
##STEP 1 Initialize Weights
x1 = 0.5
x2 = 0.3
w1 = 0.4
w2 = 0.6
b = 0.2
y = 1  

In [54]:
def for_pass(x1, x2, w1, w2, b):
    z = w1 * x1 + w2 * x2 + b
    return z

In [55]:
def sigmoid(z):
    a = 1/(1+math.e**(-z))
    return a

In [56]:
def loss_func(a,y):
    loss = -(y * math.log(a) + (1 - y) * math.log(1 - a))
    return loss

In [57]:
def back_pass(a, y, w1, w2, b, alpha):
    dz =  a - y                                                       
    dw1 = dz * x1
    dw2 = dz * x2
    db = dz
    w1 = w1 - (alpha*dw1)
    w2 = w2 - (alpha*dw2)
    b = b - (alpha*db)
    return w1,w2,b

In [58]:
alpha = 0.001
for i in range(10):
    z = for_pass(x1, x2, w1, w2, b)
    a = sigmoid(z)
    ls= loss_func(a,y)
    w1, w2, b = back_pass(a, y, w1, w2, b, alpha)
    print("-----------------------------------------------------------------------------")
    print(f'The Predicted Output a/y_hat: {a}')
    print(f'Loss is: {ls}')
    print(f'The values of w1: {w1}, w2: {w2},  b: {b},')


-----------------------------------------------------------------------------

The Predicted Output a/y_hat: 0.6410674063348171

Loss is: 0.44462066950155305

The values of w1: 0.4001794662968326, w2: 0.6001076797780995,  b: 0.2003589325936652,

-----------------------------------------------------------------------------

The Predicted Output a/y_hat: 0.6411780699402728

Loss is: 0.4444480604219687

The values of w1: 0.4003588772618625, w2: 0.6002153263571175,  b: 0.20071775452372492,

-----------------------------------------------------------------------------

The Predicted Output a/y_hat: 0.6412886844060224

Loss is: 0.4442755577576322

The values of w1: 0.40053823291965945, w2: 0.6003229397517957,  b: 0.2010764658393189,

-----------------------------------------------------------------------------

The Predicted Output a/y_hat: 0.6413992497513853

Loss is: 0.444103161428498

The values of w1: 0.40071753329478377, w2: 0.6004305199768704,  b: 0.20143506658956753,

----------------

In [59]:
w1,w2,b,ls

(0.4017921759835564,
 0.6010753055901339,
 0.20358435196711258,
 0.44307101201825644)

# Gradient Descent With n Features and 1 Example (Vectorized) (Assignment 3)

In [60]:
import numpy as np 
import pandas as pd
import time

In [61]:
data = {
    'x1': np.random.rand(1),  
    'x2': np.random.rand(1),  
    'x3': np.random.rand(1),  
    'x4': np.random.rand(1),  
    'x5': np.random.rand(1),
    'y':[1]
}
df =pd.DataFrame(data)
df


x1        x2        x3        x4        x5  y
0  0.434072  0.765072  0.088809  0.746471  0.423473  1

In [62]:
X = np.array(df.iloc[:,:-1])
print(X)

[[0.43407163 0.76507169 0.08880928 0.7464713  0.42347264]]


In [63]:
y = df.iloc[:,-1]
y = np.array(y)
print(y)

[1]


In [64]:
def cal_loss(a,y):
    loss = -(y * np.log(a)) - ((1 - y) * np.log(1 - a))
    return loss

In [65]:
def weight(X):
    num_feature = X.shape[1]
    b = 1
    W = np.ones((1, num_feature)) * 0.005
    return W, b


In [66]:
def sigmoid(z):
    a = 1/(1+np.exp(-z))
    return a

In [67]:
def forward_pass(X,W,b):
    z = np.dot(X,W.T) + b
    a = sigmoid(z)
    return z,a

In [68]:
def backpass(a,y,W,X,b,alpha):
    dz =  a - y
    dW = dz * X
    db = dz 
    W = W - (alpha*dW)
    b = b - (alpha*db)
    return W,b

In [69]:
alpha = 0.1
epochs=5
W,b = weight(X)
print(W, b)
tic =time.time()
for i in range(epochs):
    z = np.dot(X,W.T) + b
    a = sigmoid(z)
    loss = cal_loss(a,y)
    W,b = backpass(a,y,W,X,b,alpha)
    print('--------------------------------------')
    print(f'The Loss: ')
    print(f'The Predicted Output a/y_hat: {a}')
    print(f'The values of W: {W}, b: {b}\n')
toc =time.time()
print(str(1000*(toc-tic)))

[[0.005 0.005 0.005 0.005 0.005]] 1

--------------------------------------

The Loss: 

The Predicted Output a/y_hat: [[0.73346797]]

The values of W: [[0.0165694  0.02539161 0.00736705 0.02489585 0.0162869 ]], b: [[1.0266532]]



--------------------------------------

The Loss: 

The Predicted Output a/y_hat: [[0.7463818]]

The values of W: [[0.02757825 0.04479522 0.00961942 0.04382772 0.02702694]], b: [[1.05201502]]



--------------------------------------

The Loss: 

The Predicted Output a/y_hat: [[0.75828008]]

The values of W: [[0.03807062 0.06328853 0.01176611 0.06187142 0.03726312]], b: [[1.07618702]]



--------------------------------------

The Loss: 

The Predicted Output a/y_hat: [[0.76926093]]

The values of W: [[0.04808635 0.08094172 0.01381529 0.07909543 0.04703428]], b: [[1.09926092]]



--------------------------------------

The Loss: 

The Predicted Output a/y_hat: [[0.77941271]]

The values of W: [[0.05766142 0.09781823 0.01577431 0.09556164 0.05637555]], b: [[1

# *Gradient Descent With n Features and m Example (Vectorized)*

In [1]:
import numpy as np
import pandas as pd

In [30]:
data={ 
    'x1':np.random.rand(6),
    'x2':np.random.rand(6),
    'x3':np.random.rand(6),
    'x4':np.random.rand(6),
    'x5':np.random.rand(6),
    'y': np.random.randint(0, 2, size=6)
    }
df = pd.DataFrame(data)
df


x1        x2        x3        x4        x5  y
0  0.168868  0.601219  0.267110  0.211592  0.219758  1
1  0.092954  0.557325  0.811072  0.757250  0.826851  0
2  0.372966  0.126565  0.371136  0.809892  0.540994  1
3  0.614317  0.140751  0.133174  0.475918  0.126772  1
4  0.582576  0.807610  0.782733  0.770890  0.438639  0
5  0.142566  0.176886  0.274120  0.788097  0.626729  0

In [41]:
data ={
   'x1':[2,3,4,5],
   'x2':[4,6,9,10],
   'x3':[6,9,5,2],
    'x4':[8,12,2,6],
   'x5':[10,15,4,8],
    'y':[1,1,0,0]}

df = pd.DataFrame(data)
df.head()

x1  x2  x3  x4  x5  y
0   2   4   6   8  10  1
1   3   6   9  12  15  1
2   4   9   5   2   4  0
3   5  10   2   6   8  0

In [42]:
X = np.array(df.iloc[:,:-1]).T
print(X)
print(X.shape)

[[ 2  3  4  5]
 [ 4  6  9 10]
 [ 6  9  5  2]
 [ 8 12  2  6]
 [10 15  4  8]]
(5, 4)


In [43]:
y = np.array(df.iloc[:,-1]).reshape(1,-1)
print(y)
print(y.shape)

[[1 1 0 0]]
(1, 4)


In [44]:
def cal_loss(a, y):
    n,m = y.shape
    loss = -1/m * np.sum(y * np.log(a) + (1 - y) * np.log(1 - a))
    return loss

In [45]:
def weight(X):
    num_feature = X.shape[0]
    b = 1
    W = np.ones((num_feature, 1)) * 0.005  
    return W, b

In [46]:
W.shape, X.shape

((5, 1), (5, 4))

In [47]:
def sigmoid(z):
    a = 1/(1+np.exp(-z))
    return a

In [48]:
def forward_pass(X,W,b):
    z = np.dot(W.T,X) + b
    a = sigmoid(z)
    return z,a

In [49]:
def backpass(a, y, W, X, b, alpha):
    m = X.shape[1]
    dz = a - y
    dW = 1/m * np.dot(X, dz.T)
    db = 1/m * np.sum(dz)
    W = W - alpha * dW
    b = b - alpha * db
    return W, b

In [50]:
alpha = 0.001
epochs=100
W,b = weight(X)
print(W, b)

for i in range(epochs):
    z, a = forward_pass(X,W,b)
    loss = cal_loss(a,y)
    W,b = backpass(a,y,W,X,b,alpha)
    if (i+1) % 10 == 0:
        print('--------------------------------------')
        print(f'The Loss is: {loss}')
        print(f'The Predicted Output a/y_hat: {a}')
        print(f'The values of W: {W}, b: {b}\n')


[[0.005]
 [0.005]
 [0.005]
 [0.005]
 [0.005]] 1
--------------------------------------
The Loss is: 0.7504432862462113
The Predicted Output a/y_hat: [[0.71971171 0.71414525 0.69122765 0.68684239]]
The values of W: [[-0.00800901]
 [-0.02282297]
 [ 0.00209817]
 [ 0.00353072]
 [-0.0004475 ]], b: 0.9976880808550079

--------------------------------------
The Loss is: 0.6807540906257847
The Predicted Output a/y_hat: [[0.69560177 0.67734953 0.63257248 0.62062927]]
The values of W: [[-0.01891286]
 [-0.04627562]
 [ 0.00199429]
 [ 0.00566025]
 [-0.00106429]], b: 0.995929395806827

--------------------------------------
The Loss is: 0.626815593574413
The Predicted Output a/y_hat: [[0.68692518 0.66403795 0.58469097 0.569834  ]]
The values of W: [[-0.0283252 ]
 [-0.06661395]
 [ 0.00357951]
 [ 0.00990766]
 [ 0.00123501]], b: 0.9945409542314041

--------------------------------------
The Loss is: 0.581209208435119
The Predicted Output a/y_hat: [[0.68753084 0.66511045 0.54480413 0.5301579 ]]
The valu

In [53]:
W.shape

(5, 1)

# Neural Network (Assignment 4)

In [10]:

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)



In [11]:

def initialize_parameters(input_size, hidden_size, output_size):
    W1 = np.random.randn(hidden_size, input_size)
    b1 = np.ones((hidden_size, 1))
    W2 = np.random.randn(output_size, hidden_size)
    b2 = np.ones((output_size, 1))
    return W1, b1, W2, b2


In [12]:
def forward_pass(X, W1, b1, W2, b2):
    z1 = np.dot(W1, X) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(W2, a1) + b2
    a2 = sigmoid(z2)
    return a1, a2


In [13]:

def backward_pass(X, y, a1, a2, W2):
    m = X.shape[1]
    dz2 = a2 - y
    dW2 = np.dot(dz2, a1.T) / m
    db2 = np.sum(dz2, axis=1, keepdims=True) / m
    dz1 = np.dot(W2.T, dz2) * sigmoid_derivative(a1)
    dW1 = np.dot(dz1, X.T) / m
    db1 = np.sum(dz1, axis=1, keepdims=True) / m
    return dW1, db1, dW2, db2


In [14]:

def update_parameters(W1, b1, W2, b2, dW1, db1, dW2, db2, learning_rate):
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    return W1, b1, W2, b2


In [18]:
def train(X, y, input_size, hidden_size, output_size, epochs, learning_rate):
    W1, b1, W2, b2 = initialize_parameters(input_size, hidden_size, output_size)
    for epoch in range(epochs):
        a1, a2 = forward_pass(X, W1, b1, W2, b2)
        dW1, db1, dW2, db2 = backward_pass(X, y, a1, a2, W2)
        W1, b1, W2, b2 = update_parameters(W1, b1, W2, b2, dW1, db1, dW2, db2, learning_rate)
        if epoch % 5 == 0:
            loss = np.mean(np.square(a2 - y))
            print(f'Epoch {epoch}, Loss: {loss}')


In [20]:
input_size = 3
hidden_size = 4
output_size = 1

X = np.random.randn(input_size, 1)
y = np.random.randn(output_size, 1)

# Train the neural network
train(X, y, input_size, hidden_size, output_size, epochs=20, learning_rate=0.1)

Epoch 0, Loss: 2.614338222586751
Epoch 5, Loss: 1.5205398193156334
Epoch 10, Loss: 0.8219060923427748
Epoch 15, Loss: 0.6119512691625879
